{{- if and .Values.secrets.create (not .Values.secrets.existingSecret) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "agentflow.secretName" . }}
  labels:
    {{- include "agentflow.labels" . | nindent 4 }}
type: Opaque
stringData:
  AGENTFLOW_LLM_API_KEY: {{ .Values.secrets.data.llmApiKey | quote }}
  AGENTFLOW_SERVER_JWT_SECRET: {{ .Values.secrets.data.serverJWTSecret | quote }}
  AGENTFLOW_SERVER_JWT_PUBLIC_KEY: {{ .Values.secrets.data.serverJWTPublicKey | quote }}
  AGENTFLOW_REDIS_PASSWORD: {{ .Values.secrets.data.redisPassword | quote }}
  AGENTFLOW_DATABASE_PASSWORD: {{ .Values.secrets.data.databasePassword | quote }}
  AGENTFLOW_MONGODB_PASSWORD: {{ .Values.secrets.data.mongodbPassword | quote }}
{{- end }}
