# =============================================================================
# Codecov Configuration for AgentFlow
# =============================================================================
# Documentation: https://docs.codecov.com/docs/codecov-yaml
# Validator: https://api.codecov.io/validate
# =============================================================================

codecov:
  # Require CI to pass before processing coverage
  require_ci_to_pass: true
  # Wait for all CI jobs to complete before posting status
  notify:
    wait_for_ci: true

coverage:
  # Coverage precision (number of decimal places)
  precision: 2
  # Rounding method: down, up, nearest
  round: down
  # Range for coverage colors (red to green)
  range: "20...80"

  status:
    # Project-level coverage status
    project:
      default:
        # Target coverage percentage
        target: auto
        # Allow coverage to drop by this percentage
        threshold: 1%
        # Only check coverage on changed files
        only_pulls: false
        # Flags to include
        flags:
          - unittests

      # Key paths coverage (core modules)
      key-paths:
        target: 30%
        threshold: 2%
        paths:
          - "types/"
          - "llm/"
          - "rag/"
          - "workflow/"
          - "agent/"
        flags:
          - unittests

    # Patch-level coverage (new/changed code)
    patch:
      default:
        # Target coverage for new code
        target: 50%
        # Allow some flexibility
        threshold: 5%
        only_pulls: true

# Flags for different test types
flags:
  unittests:
    paths:
      - "!tests/e2e/"
      - "!tests/integration/"
    carryforward: true

  integration:
    paths:
      - "tests/integration/"
    carryforward: true

  e2e:
    paths:
      - "tests/e2e/"
    carryforward: true

# Ignore certain paths from coverage
ignore:
  - "**/*_test.go"
  - "**/mock_*.go"
  - "**/mocks/"
  - "examples/"
  - "docs/"
  - "scripts/"
  - "cmd/"
  - "vendor/"
  - "testdata/"

# Comment configuration for PRs
comment:
  # Post comment on PRs
  layout: "reach,diff,flags,files"
  # Comment behavior: default, once, new, off
  behavior: default
  # Require changes to post comment
  require_changes: true
  # Require base coverage to post comment
  require_base: false
  # Require head coverage to post comment
  require_head: true
  # Hide project coverage if unchanged
  hide_project_coverage: false

# GitHub Checks annotations
github_checks:
  annotations: true

# Parsers configuration
parsers:
  go:
    partials_as_hits: true
