package runtime

import legacy "github.com/BaSui01/agentflow/agent/execution/runtime"

// This file completes the public agent/runtime surface while the implementation
// is being physically migrated out of agent/execution/runtime. Do not add new
// public entrypoints here; move implementations into agent/runtime instead.

type AgentBuilder = legacy.AgentBuilder
type AgentFactory = legacy.AgentFactory
type AgentRunCompleteEvent = legacy.AgentRunCompleteEvent
type AgentRunErrorEvent = legacy.AgentRunErrorEvent
type AgentRunStartEvent = legacy.AgentRunStartEvent
type AgentTool = legacy.AgentTool
type AgentToolConfig = legacy.AgentToolConfig
type AsyncExecution = legacy.AsyncExecution
type AsyncExecutor = legacy.AsyncExecutor
type ChatProvider = legacy.ChatProvider
type ChatRequest = legacy.ChatRequest
type ChatResponse = legacy.ChatResponse
type CheckpointDiff = legacy.CheckpointDiff
type CheckpointStore = legacy.CheckpointStore
type CheckpointVersion = legacy.CheckpointVersion
type CodeTaskLoopValidator = legacy.CodeTaskLoopValidator
type CodeValidationLanguage = legacy.CodeValidationLanguage
type CodeValidator = legacy.CodeValidator
type CompletionDecision = legacy.CompletionDecision
type CompletionJudge = legacy.CompletionJudge
type ContextManager = legacy.ContextManager
type ConversationDoc = legacy.ConversationDoc
type ConversationMessage = legacy.ConversationMessage
type ConversationStoreProvider = legacy.ConversationStoreProvider
type ConversationUpdate = legacy.ConversationUpdate
type Critique = legacy.Critique
type DefaultCompletionJudge = legacy.DefaultCompletionJudge
type DefaultExecutionOptionsResolver = legacy.DefaultExecutionOptionsResolver
type DefaultLoopValidator = legacy.DefaultLoopValidator
type DefaultReasoningModeSelector = legacy.DefaultReasoningModeSelector
type DefaultToolProtocolRuntime = legacy.DefaultToolProtocolRuntime
type DefensivePromptConfig = legacy.DefensivePromptConfig
type DefensivePromptEnhancer = legacy.DefensivePromptEnhancer
type DockerBackend = legacy.DockerBackend
type DockerBackendConfig = legacy.DockerBackendConfig
type DynamicToolSelector = legacy.DynamicToolSelector
type DynamicToolSelectorRunner = legacy.DynamicToolSelectorRunner
type EnhancedExecutionOptions = legacy.EnhancedExecutionOptions
type EnhancedMemoryRunner = legacy.EnhancedMemoryRunner
type EphemeralPromptLayerBuilder = legacy.EphemeralPromptLayerBuilder
type EphemeralPromptLayerInput = legacy.EphemeralPromptLayerInput
type ErrInvalidTransition = legacy.ErrInvalidTransition
type Error = legacy.Error
type Example = legacy.Example
type Execution = legacy.Execution
type ExecutionBackend = legacy.ExecutionBackend
type ExecutionCheckpoint = legacy.ExecutionCheckpoint
type ExecutionCheckpointStore = legacy.ExecutionCheckpointStore
type ExecutionEvent = legacy.ExecutionEvent
type ExecutionEventType = legacy.ExecutionEventType
type ExecutionFunc = legacy.ExecutionFunc
type ExecutionMiddleware = legacy.ExecutionMiddleware
type ExecutionOptionsResolver = legacy.ExecutionOptionsResolver
type ExecutionPipeline = legacy.ExecutionPipeline
type ExecutionSession = legacy.ExecutionSession
type ExecutionState = legacy.ExecutionState
type ExecutionStatus = legacy.ExecutionStatus
type Executor = legacy.Executor
type ExecutorConfig = legacy.ExecutorConfig
type ExecutorOption = legacy.ExecutorOption
type ExecutorStats = legacy.ExecutorStats
type ExplainabilityRecorder = legacy.ExplainabilityRecorder
type ExplainabilitySynopsisReader = legacy.ExplainabilitySynopsisReader
type ExplainabilitySynopsisSnapshot = legacy.ExplainabilitySynopsisSnapshot
type ExplainabilitySynopsisSnapshotReader = legacy.ExplainabilitySynopsisSnapshotReader
type ExplainabilityTimelineRecorder = legacy.ExplainabilityTimelineRecorder
type ExtensionRegistry = legacy.ExtensionRegistry
type FailureMode = legacy.FailureMode
type FeedbackEvent = legacy.FeedbackEvent
type FileCheckpointStore = legacy.FileCheckpointStore
type GenericLoopValidator = legacy.GenericLoopValidator
type GuardRail = legacy.GuardRail
type GuardrailsError = legacy.GuardrailsError
type GuardrailsErrorType = legacy.GuardrailsErrorType
type GuardrailsManager = legacy.GuardrailsManager
type HealthStatus = legacy.HealthStatus
type InjectionDefenseConfig = legacy.InjectionDefenseConfig
type LSPClientRunner = legacy.LSPClientRunner
type LSPLifecycleOwner = legacy.LSPLifecycleOwner
type LifecycleManager = legacy.LifecycleManager
type LoopControlPolicy = legacy.LoopControlPolicy
type LoopDecision = legacy.LoopDecision
type LoopExecutor = legacy.LoopExecutor
type LoopObservation = legacy.LoopObservation
type LoopObserveFunc = legacy.LoopObserveFunc
type LoopPlannerFunc = legacy.LoopPlannerFunc
type LoopReflectionFunc = legacy.LoopReflectionFunc
type LoopReflectionResult = legacy.LoopReflectionResult
type LoopStage = legacy.LoopStage
type LoopState = legacy.LoopState
type LoopStepExecutorFunc = legacy.LoopStepExecutorFunc
type LoopValidationFunc = legacy.LoopValidationFunc
type LoopValidationFuncAdapter = legacy.LoopValidationFuncAdapter
type LoopValidationIssue = legacy.LoopValidationIssue
type LoopValidationResult = legacy.LoopValidationResult
type LoopValidationStatus = legacy.LoopValidationStatus
type LoopValidator = legacy.LoopValidator
type LoopValidatorChain = legacy.LoopValidatorChain
type MCPServerRunner = legacy.MCPServerRunner
type ManagedLSP = legacy.ManagedLSP
type MemoryCache = legacy.MemoryCache
type MemoryConfig = legacy.MemoryConfig
type MemoryCoordinator = legacy.MemoryCoordinator
type MemoryKind = legacy.MemoryKind
type MemoryObservationInput = legacy.MemoryObservationInput
type MemoryReader = legacy.MemoryReader
type MemoryRecallOptions = legacy.MemoryRecallOptions
type MemoryRecord = legacy.MemoryRecord
type MemoryRuntime = legacy.MemoryRuntime
type MemoryWriter = legacy.MemoryWriter
type NamedStep = legacy.NamedStep
type ObservabilityRunner = legacy.ObservabilityRunner
type OrchestrationTaskInput = legacy.OrchestrationTaskInput
type OrchestrationTaskOutput = legacy.OrchestrationTaskOutput
type OrchestratorRunner = legacy.OrchestratorRunner
type OutputSchema = legacy.OutputSchema
type PersistenceStores = legacy.PersistenceStores
type PersistentCheckpointStore = legacy.PersistentCheckpointStore
type PlanConfig = legacy.PlanConfig
type PreparedToolProtocol = legacy.PreparedToolProtocol
type ProcessBackend = legacy.ProcessBackend
type ProcessBackendConfig = legacy.ProcessBackendConfig
type PromptBundle = legacy.PromptBundle
type PromptDocument = legacy.PromptDocument
type PromptEnhancer = legacy.PromptEnhancer
type PromptEnhancerConfig = legacy.PromptEnhancerConfig
type PromptEnhancerRunner = legacy.PromptEnhancerRunner
type PromptOptimizer = legacy.PromptOptimizer
type PromptStoreProvider = legacy.PromptStoreProvider
type PromptTemplate = legacy.PromptTemplate
type PromptTemplateLibrary = legacy.PromptTemplateLibrary
type ProviderAdapter = legacy.ProviderAdapter
type RealDockerBackend = legacy.RealDockerBackend
type RealtimeCoordinator = legacy.RealtimeCoordinator
type ReasoningExposureLevel = legacy.ReasoningExposureLevel
type ReasoningModeSelector = legacy.ReasoningModeSelector
type ReasoningRuntime = legacy.ReasoningRuntime
type ReasoningSelection = legacy.ReasoningSelection
type ReflectionConfig = legacy.ReflectionConfig
type ReflectionExecutor = legacy.ReflectionExecutor
type ReflectionExecutorConfig = legacy.ReflectionExecutorConfig
type ReflectionResult = legacy.ReflectionResult
type ReflectionRunner = legacy.ReflectionRunner
type RemoteToolTarget = legacy.RemoteToolTarget
type RemoteToolTargetKind = legacy.RemoteToolTargetKind
type RemoteToolTransport = legacy.RemoteToolTransport
type Reranker = legacy.Reranker
type RetrievalProvider = legacy.RetrievalProvider
type RetrievalStep = legacy.RetrievalStep
type RetrievalStepRequest = legacy.RetrievalStepRequest
type RetrievalStepResult = legacy.RetrievalStepResult
type Retriever = legacy.Retriever
type RunDoc = legacy.RunDoc
type RunOutputDoc = legacy.RunOutputDoc
type RunStoreProvider = legacy.RunStoreProvider
type RuntimeStreamEventType = legacy.RuntimeStreamEventType
type SDKRunItemEventName = legacy.SDKRunItemEventName
type SDKStreamEventType = legacy.SDKStreamEventType
type SandboxCodeValidator = legacy.SandboxCodeValidator
type SandboxTool = legacy.SandboxTool
type ScopedPersistenceStores = legacy.ScopedPersistenceStores
type SimpleEventBus = legacy.SimpleEventBus
type SkillDiscoverer = legacy.SkillDiscoverer
type StateChangeEvent = legacy.StateChangeEvent
type StepFunc = legacy.StepFunc
type StepRegistry = legacy.StepRegistry
type StopReason = legacy.StopReason
type StreamChunk = legacy.StreamChunk
type SubagentCompletedEvent = legacy.SubagentCompletedEvent
type SubagentManager = legacy.SubagentManager
type SystemPrompt = legacy.SystemPrompt
type TaskRecord = legacy.TaskRecord
type TaskStoreAdapter = legacy.TaskStoreAdapter
type TaskStoreBridge = legacy.TaskStoreBridge
type ToolCallEvent = legacy.ToolCallEvent
type ToolExecutorAdapter = legacy.ToolExecutorAdapter
type ToolInvocationRequest = legacy.ToolInvocationRequest
type ToolInvocationResult = legacy.ToolInvocationResult
type ToolProtocolRuntime = legacy.ToolProtocolRuntime
type ToolResult = legacy.ToolResult
type ToolScore = legacy.ToolScore
type ToolSelectionConfig = legacy.ToolSelectionConfig
type ToolSelector = legacy.ToolSelector
type ToolStateProvider = legacy.ToolStateProvider
type ToolStats = legacy.ToolStats
type ToolVerificationLoopValidator = legacy.ToolVerificationLoopValidator
type TraceFeedbackAction = legacy.TraceFeedbackAction
type TraceFeedbackConfig = legacy.TraceFeedbackConfig
type TraceFeedbackPlan = legacy.TraceFeedbackPlan
type TraceFeedbackPlanAdapter = legacy.TraceFeedbackPlanAdapter
type TraceFeedbackPlanner = legacy.TraceFeedbackPlanner
type TraceFeedbackSignals = legacy.TraceFeedbackSignals
type UnifiedMemoryFacade = legacy.UnifiedMemoryFacade

const (
	CodeLangBash = legacy.CodeLangBash
	CodeLangGo = legacy.CodeLangGo
	CodeLangJavaScript = legacy.CodeLangJavaScript
	CodeLangPython = legacy.CodeLangPython
	CodeLangRust = legacy.CodeLangRust
	CodeLangTypeScript = legacy.CodeLangTypeScript
	DefaultStreamInactivityTimeout = legacy.DefaultStreamInactivityTimeout
	EventAgentRunComplete = legacy.EventAgentRunComplete
	EventAgentRunError = legacy.EventAgentRunError
	EventAgentRunStart = legacy.EventAgentRunStart
	EventApprovalRequested = legacy.EventApprovalRequested
	EventApprovalResponded = legacy.EventApprovalResponded
	EventFeedback = legacy.EventFeedback
	EventStateChange = legacy.EventStateChange
	EventSubagentCompleted = legacy.EventSubagentCompleted
	EventToolCall = legacy.EventToolCall
	ExecutionEventCheckpointed = legacy.ExecutionEventCheckpointed
	ExecutionEventPaused = legacy.ExecutionEventPaused
	ExecutionEventResumed = legacy.ExecutionEventResumed
	ExecutionEventStepCompleted = legacy.ExecutionEventStepCompleted
	ExecutionEventStepFailed = legacy.ExecutionEventStepFailed
	ExecutionEventStepStarted = legacy.ExecutionEventStepStarted
	ExecutionStateCancelled = legacy.ExecutionStateCancelled
	ExecutionStateCompleted = legacy.ExecutionStateCompleted
	ExecutionStateFailed = legacy.ExecutionStateFailed
	ExecutionStateInitialized = legacy.ExecutionStateInitialized
	ExecutionStatePaused = legacy.ExecutionStatePaused
	ExecutionStateResuming = legacy.ExecutionStateResuming
	ExecutionStateRunning = legacy.ExecutionStateRunning
	ExecutionStatusCanceled = legacy.ExecutionStatusCanceled
	ExecutionStatusCompleted = legacy.ExecutionStatusCompleted
	ExecutionStatusFailed = legacy.ExecutionStatusFailed
	ExecutionStatusPending = legacy.ExecutionStatusPending
	ExecutionStatusRunning = legacy.ExecutionStatusRunning
	GuardrailsErrorTypeInput = legacy.GuardrailsErrorTypeInput
	GuardrailsErrorTypeOutput = legacy.GuardrailsErrorTypeOutput
	LoopDecisionContinue = legacy.LoopDecisionContinue
	LoopDecisionDone = legacy.LoopDecisionDone
	LoopDecisionEscalate = legacy.LoopDecisionEscalate
	LoopDecisionReflect = legacy.LoopDecisionReflect
	LoopDecisionReplan = legacy.LoopDecisionReplan
	LoopStageAct = legacy.LoopStageAct
	LoopStageAnalyze = legacy.LoopStageAnalyze
	LoopStageDecideNext = legacy.LoopStageDecideNext
	LoopStageEvaluate = legacy.LoopStageEvaluate
	LoopStageObserve = legacy.LoopStageObserve
	LoopStagePerceive = legacy.LoopStagePerceive
	LoopStagePlan = legacy.LoopStagePlan
	LoopStageValidate = legacy.LoopStageValidate
	LoopValidationStatusFailed = legacy.LoopValidationStatusFailed
	LoopValidationStatusPassed = legacy.LoopValidationStatusPassed
	LoopValidationStatusPending = legacy.LoopValidationStatusPending
	MemoryEpisodic = legacy.MemoryEpisodic
	MemoryLongTerm = legacy.MemoryLongTerm
	MemoryProcedural = legacy.MemoryProcedural
	MemorySemantic = legacy.MemorySemantic
	MemoryShortTerm = legacy.MemoryShortTerm
	MemoryWorking = legacy.MemoryWorking
	ReasoningExposureAdvanced = legacy.ReasoningExposureAdvanced
	ReasoningExposureAll = legacy.ReasoningExposureAll
	ReasoningExposureOfficial = legacy.ReasoningExposureOfficial
	ReasoningModeDynamicPlanner = legacy.ReasoningModeDynamicPlanner
	ReasoningModePlanAndExecute = legacy.ReasoningModePlanAndExecute
	ReasoningModeReWOO = legacy.ReasoningModeReWOO
	ReasoningModeReact = legacy.ReasoningModeReact
	ReasoningModeReflection = legacy.ReasoningModeReflection
	ReasoningModeTreeOfThought = legacy.ReasoningModeTreeOfThought
	RemoteToolTargetA2A = legacy.RemoteToolTargetA2A
	RemoteToolTargetHTTP = legacy.RemoteToolTargetHTTP
	RemoteToolTargetMCP = legacy.RemoteToolTargetMCP
	RemoteToolTargetStdio = legacy.RemoteToolTargetStdio
	SDKAgentUpdatedEvent = legacy.SDKAgentUpdatedEvent
	SDKApprovalRequested = legacy.SDKApprovalRequested
	SDKApprovalResponse = legacy.SDKApprovalResponse
	SDKHandoffRequested = legacy.SDKHandoffRequested
	SDKMCPApprovalRequested = legacy.SDKMCPApprovalRequested
	SDKMCPApprovalResponse = legacy.SDKMCPApprovalResponse
	SDKMCPListTools = legacy.SDKMCPListTools
	SDKMessageOutputCreated = legacy.SDKMessageOutputCreated
	SDKRawResponseEvent = legacy.SDKRawResponseEvent
	SDKReasoningCreated = legacy.SDKReasoningCreated
	SDKRunItemEvent = legacy.SDKRunItemEvent
	SDKToolCalled = legacy.SDKToolCalled
	SDKToolOutput = legacy.SDKToolOutput
	SDKToolSearchCalled = legacy.SDKToolSearchCalled
	SDKToolSearchOutput = legacy.SDKToolSearchOutput
	SteeringTypeGuide = legacy.SteeringTypeGuide
	SteeringTypeStopAndSend = legacy.SteeringTypeStopAndSend
	StopReasonBlocked = legacy.StopReasonBlocked
	StopReasonMaxIterations = legacy.StopReasonMaxIterations
	StopReasonNeedHuman = legacy.StopReasonNeedHuman
	StopReasonSolved = legacy.StopReasonSolved
	StopReasonTimeout = legacy.StopReasonTimeout
	StopReasonToolFailureUnrecoverable = legacy.StopReasonToolFailureUnrecoverable
	StopReasonValidationFailed = legacy.StopReasonValidationFailed
	TraceFeedbackHistoryOnly = legacy.TraceFeedbackHistoryOnly
	TraceFeedbackMemoryRecallOnly = legacy.TraceFeedbackMemoryRecallOnly
	TraceFeedbackSkip = legacy.TraceFeedbackSkip
	TraceFeedbackSynopsisAndHistory = legacy.TraceFeedbackSynopsisAndHistory
	TraceFeedbackSynopsisOnly = legacy.TraceFeedbackSynopsisOnly
)

var (
	AsPromptEnhancerRunner = legacy.AsPromptEnhancerRunner
	AsReflectionRunner = legacy.AsReflectionRunner
	AsToolSelectorRunner = legacy.AsToolSelectorRunner
	CanTransition = legacy.CanTransition
	CreateAgent = legacy.CreateAgent
	DefaultDefensivePromptConfig = legacy.DefaultDefensivePromptConfig
	DefaultEnhancedExecutionOptions = legacy.DefaultEnhancedExecutionOptions
	DefaultExecutorConfig = legacy.DefaultExecutorConfig
	DefaultPromptEnhancerConfig = legacy.DefaultPromptEnhancerConfig
	DefaultReflectionConfig = legacy.DefaultReflectionConfig
	DefaultReflectionExecutorConfig = legacy.DefaultReflectionExecutorConfig
	DefaultToolSelectionConfig = legacy.DefaultToolSelectionConfig
	DefaultTraceFeedbackConfig = legacy.DefaultTraceFeedbackConfig
	DurationPtr = legacy.DurationPtr
	EnsureImages = legacy.EnsureImages
	Float32Ptr = legacy.Float32Ptr
	GenerateCheckpointID = legacy.GenerateCheckpointID
	GetErrorCode = legacy.GetErrorCode
	InitGlobalRegistry = legacy.InitGlobalRegistry
	IntPtr = legacy.IntPtr
	IsRetryable = legacy.IsRetryable
	MergeRunConfig = legacy.MergeRunConfig
	NewAgentTool = legacy.NewAgentTool
	NewAsyncExecutor = legacy.NewAsyncExecutor
	NewCheckpointManager = legacy.NewCheckpointManager
	NewCodeTaskLoopValidator = legacy.NewCodeTaskLoopValidator
	NewCodeValidator = legacy.NewCodeValidator
	NewComposedTraceFeedbackPlanner = legacy.NewComposedTraceFeedbackPlanner
	NewDefaultCompletionJudge = legacy.NewDefaultCompletionJudge
	NewDefaultExecutionOptionsResolver = legacy.NewDefaultExecutionOptionsResolver
	NewDefaultLoopValidator = legacy.NewDefaultLoopValidator
	NewDefaultMemoryRuntime = legacy.NewDefaultMemoryRuntime
	NewDefaultReasoningModeSelector = legacy.NewDefaultReasoningModeSelector
	NewDefaultReasoningRegistry = legacy.NewDefaultReasoningRegistry
	NewDefaultReasoningRuntime = legacy.NewDefaultReasoningRuntime
	NewDefaultRemoteToolTransport = legacy.NewDefaultRemoteToolTransport
	NewDefaultToolProtocolRuntime = legacy.NewDefaultToolProtocolRuntime
	NewDefensivePromptEnhancer = legacy.NewDefensivePromptEnhancer
	NewDockerBackend = legacy.NewDockerBackend
	NewDockerBackendWithConfig = legacy.NewDockerBackendWithConfig
	NewDynamicToolSelector = legacy.NewDynamicToolSelector
	NewEphemeralPromptLayerBuilder = legacy.NewEphemeralPromptLayerBuilder
	NewError = legacy.NewError
	NewErrorWithCause = legacy.NewErrorWithCause
	NewEventBus = legacy.NewEventBus
	NewExecutionPipeline = legacy.NewExecutionPipeline
	NewExecutor = legacy.NewExecutor
	NewExtensionRegistry = legacy.NewExtensionRegistry
	NewFileCheckpointStore = legacy.NewFileCheckpointStore
	NewGuardrailsCoordinator = legacy.NewGuardrailsCoordinator
	NewGuardrailsManager = legacy.NewGuardrailsManager
	NewHintTraceFeedbackAdapter = legacy.NewHintTraceFeedbackAdapter
	NewLifecycleManager = legacy.NewLifecycleManager
	NewLoopState = legacy.NewLoopState
	NewLoopValidatorChain = legacy.NewLoopValidatorChain
	NewManagedLSP = legacy.NewManagedLSP
	NewMemoryCache = legacy.NewMemoryCache
	NewMemoryCoordinator = legacy.NewMemoryCoordinator
	NewPersistenceStores = legacy.NewPersistenceStores
	NewPersistentCheckpointStore = legacy.NewPersistentCheckpointStore
	NewProcessBackend = legacy.NewProcessBackend
	NewProcessBackendWithConfig = legacy.NewProcessBackendWithConfig
	NewPromptBundleFromIdentity = legacy.NewPromptBundleFromIdentity
	NewPromptEnhancer = legacy.NewPromptEnhancer
	NewPromptOptimizer = legacy.NewPromptOptimizer
	NewPromptTemplateLibrary = legacy.NewPromptTemplateLibrary
	NewProviderAdapter = legacy.NewProviderAdapter
	NewRealDockerBackend = legacy.NewRealDockerBackend
	NewRealtimeCoordinator = legacy.NewRealtimeCoordinator
	NewReasoningRegistryForExposure = legacy.NewReasoningRegistryForExposure
	NewReflectionExecutor = legacy.NewReflectionExecutor
	NewRetrievalStep = legacy.NewRetrievalStep
	NewRuleBasedTraceFeedbackPlanner = legacy.NewRuleBasedTraceFeedbackPlanner
	NewSandboxCodeValidator = legacy.NewSandboxCodeValidator
	NewSandboxTool = legacy.NewSandboxTool
	NewScopedPersistenceStores = legacy.NewScopedPersistenceStores
	NewSteeringChannel = legacy.NewSteeringChannel
	NewStepRegistry = legacy.NewStepRegistry
	NewSubagentManager = legacy.NewSubagentManager
	NewTaskStoreBridge = legacy.NewTaskStoreBridge
	NewUnifiedMemoryFacade = legacy.NewUnifiedMemoryFacade
	OutputFromReasoningResult = legacy.OutputFromReasoningResult
	PullImage = legacy.PullImage
	ResolveRunConfig = legacy.ResolveRunConfig
	RunConfigFromInputContext = legacy.RunConfigFromInputContext
	SteeringChannelFromContext = legacy.SteeringChannelFromContext
	TraceFeedbackConfigFromAgentConfig = legacy.TraceFeedbackConfigFromAgentConfig
	WithCheckpointStore = legacy.WithCheckpointStore
	WithRuntimeConversationMessages = legacy.WithRuntimeConversationMessages
)

var (
	ErrProviderNotSet = legacy.ErrProviderNotSet
	GlobalRegistry = legacy.GlobalRegistry
	SDKHandoffOccured = legacy.SDKHandoffOccured
)
