#!/usr/bin/env python3
"""Generate typed clone helpers for types/execution_options.go.

The generator is intentionally dependency-free so the leaf-level `types` package
keeps avoiding project imports and JSON round-trips.
"""
from __future__ import annotations

from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
TARGET = ROOT / "types" / "execution_options_clone_gen.go"

BODY = r'''// Code generated by scripts/generate_execution_options_clone.py; DO NOT EDIT.
package types

func cloneExecutionStrings(values []string) []string {
	if len(values) == 0 {
		return nil
	}
	return append([]string(nil), values...)
}

func cloneExecutionMetadata(values map[string]string) map[string]string {
	if len(values) == 0 {
		return nil
	}
	cloned := make(map[string]string, len(values))
	for key, value := range values {
		cloned[key] = value
	}
	return cloned
}

func cloneExecutionScalarPtr[T any](value *T) *T {
	if value == nil {
		return nil
	}
	out := *value
	return &out
}

func cloneExecutionIntPtr(value *int) *int { return cloneExecutionScalarPtr(value) }

func cloneExecutionFloat32Ptr(value *float32) *float32 { return cloneExecutionScalarPtr(value) }

func cloneExecutionInt32Ptr(value *int32) *int32 { return cloneExecutionScalarPtr(value) }

func cloneExecutionStringPtr(value *string) *string { return cloneExecutionScalarPtr(value) }

func cloneExecutionBoolPtr(value *bool) *bool { return cloneExecutionScalarPtr(value) }

func cloneToolChoice(choice *ToolChoice) *ToolChoice {
	if choice == nil {
		return nil
	}
	cloned := *choice
	cloned.AllowedTools = cloneExecutionStrings(choice.AllowedTools)
	cloned.DisableParallelToolUse = cloneExecutionScalarPtr(choice.DisableParallelToolUse)
	cloned.IncludeServerSideToolInvocations = cloneExecutionScalarPtr(choice.IncludeServerSideToolInvocations)
	return &cloned
}

func cloneResponseFormat(value *ResponseFormat) *ResponseFormat {
	if value == nil {
		return nil
	}
	cloned := *value
	if value.JSONSchema != nil {
		schema := *value.JSONSchema
		if len(value.JSONSchema.Schema) > 0 {
			schema.Schema = cloneJSONSchemaMap(value.JSONSchema.Schema)
		}
		if value.JSONSchema.Strict != nil {
			strict := *value.JSONSchema.Strict
			schema.Strict = &strict
		}
		cloned.JSONSchema = &schema
	}
	return &cloned
}

func cloneStreamOptions(value *StreamOptions) *StreamOptions {
	if value == nil {
		return nil
	}
	cloned := *value
	return &cloned
}

func cloneCacheControl(value *CacheControl) *CacheControl {
	if value == nil {
		return nil
	}
	cloned := *value
	return &cloned
}

func cloneJSONSchemaMap(value map[string]any) map[string]any {
	if len(value) == 0 {
		return nil
	}
	cloned := make(map[string]any, len(value))
	for key, item := range value {
		cloned[key] = item
	}
	return cloned
}

func cloneWebSearchOptions(value *WebSearchOptions) *WebSearchOptions {
	if value == nil {
		return nil
	}
	cloned := *value
	cloned.AllowedDomains = cloneExecutionStrings(value.AllowedDomains)
	cloned.BlockedDomains = cloneExecutionStrings(value.BlockedDomains)
	if value.UserLocation != nil {
		location := *value.UserLocation
		cloned.UserLocation = &location
	}
	return &cloned
}

func cloneContextConfig(value *ContextConfig) *ContextConfig {
	if value == nil {
		return nil
	}
	cloned := *value
	return &cloned
}

func cloneReflectionConfig(value *ReflectionConfig) *ReflectionConfig {
	if value == nil {
		return nil
	}
	cloned := *value
	return &cloned
}

func cloneGuardrailsConfig(value *GuardrailsConfig) *GuardrailsConfig {
	if value == nil {
		return nil
	}
	cloned := *value
	cloned.BlockedKeywords = cloneExecutionStrings(value.BlockedKeywords)
	return &cloned
}

func cloneMemoryConfig(value *MemoryConfig) *MemoryConfig {
	if value == nil {
		return nil
	}
	cloned := *value
	return &cloned
}

func cloneMemoryExternalContextPolicy(value *MemoryExternalContextPolicy) *MemoryExternalContextPolicy {
	if value == nil {
		return nil
	}
	cloned := *value
	return &cloned
}

func cloneSubagentExecutionPolicy(value *SubagentExecutionPolicy) *SubagentExecutionPolicy {
	if value == nil {
		return nil
	}
	cloned := *value
	cloned.AllowHandoffs = cloneExecutionScalarPtr(value.AllowHandoffs)
	return &cloned
}

'''


def main() -> None:
    TARGET.write_text(BODY, encoding="utf-8")


if __name__ == "__main__":
    main()
