package agent

import (
	"context"
	"encoding/json"
	"strings"
	"sync/atomic"
	"testing"

	"github.com/BaSui01/agentflow/llm"
	"github.com/BaSui01/agentflow/types"
	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
	"go.uber.org/zap"
)

// TestToolProvider_NilFallback 不设置 toolProvider 时，所有调用走 provider
func TestToolProvider_NilFallback(t *testing.T) {
	logger := zap.NewNop()

	mockResp := &llm.ChatResponse{
		ID:       "resp-1",
		Provider: "main",
		Model:    "claude-sonnet-4-6",
		Choices: []llm.ChatChoice{{
			Index:        0,
			FinishReason: "stop",
			Message:      types.Message{Role: llm.RoleAssistant, Content: "Hello from main!"},
		}},
	}

	var completionCalled atomic.Int32
	mainProvider := &testProvider{
		name: "main",
		completionFn: func(ctx context.Context, req *llm.ChatRequest) (*llm.ChatResponse, error) {
			completionCalled.Add(1)
			return mockResp, nil
		},
	}
	bus := &testEventBus{}

	config := testAgentConfig("test-dual", "Dual Model Agent", "claude-sonnet-4-6")

	agent := BuildBaseAgent(config, testGatewayFromProvider(mainProvider), nil, nil, bus, logger, nil)

	// toolProvider 应该为 nil
	assert.Nil(t, testToolProvider(agent), "toolProvider 未设置时应为 nil")
	assert.Equal(t, mainProvider, testMainProvider(agent), "主 provider 应正确返回")

	resp, err := agent.ChatCompletion(context.Background(), []types.Message{
		{Role: llm.RoleUser, Content: "Hi"},
	})

	assert.NoError(t, err)
	assert.Equal(t, "Hello from main!", resp.Choices[0].Message.Content)
	assert.Equal(t, int32(1), completionCalled.Load())
}

// TestToolProvider_SetAndGet 测试 SetToolProvider 和 ToolProvider 访问器
func TestToolProvider_SetAndGet(t *testing.T) {
	logger := zap.NewNop()
	mainProvider := &testProvider{name: "main"}
	toolProvider := &testProvider{name: "tool"}

	config := testAgentConfig("test-dual", "Dual Model Agent", "claude-sonnet-4-6")

	agent := BuildBaseAgent(config, testGatewayFromProvider(mainProvider), nil, nil, nil, logger, nil)

	// 初始为 nil
	assert.Nil(t, testToolProvider(agent))

	// 设置 toolProvider
	setTestToolProvider(agent, toolProvider)
	assert.Equal(t, toolProvider, testToolProvider(agent), "SetToolProvider 后应能正确获取")

	// 清除 toolProvider
	setTestToolProvider(agent, nil)
	assert.Nil(t, testToolProvider(agent), "设置为 nil 后应恢复")
}

// TestToolProvider_NoToolsUsesMainProvider 无工具时，即使设置了 toolProvider，也走主 provider
func TestToolProvider_NoToolsUsesMainProvider(t *testing.T) {
	logger := zap.NewNop()

	mockResp := &llm.ChatResponse{
		ID:       "resp-main",
		Provider: "main-provider",
		Model:    "claude-sonnet-4-6",
		Choices: []llm.ChatChoice{{
			Index:        0,
			FinishReason: "stop",
			Message:      types.Message{Role: llm.RoleAssistant, Content: "Generated by main"},
		}},
	}

	var mainCalled, toolCalled atomic.Int32
	mainProvider := &testProvider{
		name: "main-provider",
		completionFn: func(ctx context.Context, req *llm.ChatRequest) (*llm.ChatResponse, error) {
			mainCalled.Add(1)
			return mockResp, nil
		},
	}
	toolProvider := &testProvider{
		name: "tool-provider",
		completionFn: func(ctx context.Context, req *llm.ChatRequest) (*llm.ChatResponse, error) {
			toolCalled.Add(1)
			return nil, nil
		},
	}

	config := testAgentConfig("test-dual", "Dual Model Agent", "claude-sonnet-4-6")

	agent := BuildBaseAgent(config, testGatewayFromProvider(mainProvider), nil, nil, nil, logger, nil)
	setTestToolProvider(agent, toolProvider)

	resp, err := agent.ChatCompletion(context.Background(), []types.Message{
		{Role: llm.RoleUser, Content: "Write a poem"},
	})

	assert.NoError(t, err)
	assert.Equal(t, "Generated by main", resp.Choices[0].Message.Content)
	assert.Equal(t, "main-provider", resp.Provider)
	assert.Equal(t, int32(1), mainCalled.Load(), "mainProvider should be called once")
	assert.Equal(t, int32(0), toolCalled.Load(), "toolProvider should not be called")
}

// TestToolProvider_Builder 测试 Builder 的 WithToolProvider 链式调用
func TestToolProvider_Builder(t *testing.T) {
	logger := zap.NewNop()
	mainProvider := &testProvider{name: "main"}
	toolProvider := &testProvider{name: "tool"}

	config := testAgentConfig("test-builder-dual", "Builder Dual Agent", "claude-sonnet-4-6")

	agent, err := NewAgentBuilder(config).WithGateway(testGatewayFromProvider(
		mainProvider)).
		WithToolGateway(testGatewayFromProvider(

			toolProvider)).
		WithLogger(logger).
		Build()

	assert.NoError(t, err)
	assert.NotNil(t, agent)
	assert.Equal(t, mainProvider, testMainProvider(agent), "主 provider 应正确设置")
	assert.Equal(t, toolProvider, testToolProvider(agent), "toolProvider 应通过 Builder 正确注入")
}

// TestToolProvider_XMLFallback_ChatCompletion 不支持原生 FC 时自动降级到 XML 模式
func TestToolProvider_XMLFallback_ChatCompletion(t *testing.T) {
	logger := zap.NewNop()
	mainProvider := &testProvider{name: "main"}

	// toolProvider 不支持原生函数调用 → 应自动降级到 XML 模式
	var capturedReq *llm.ChatRequest
	toolProvider := &testProvider{
		name:           "cheap-model",
		supportsNative: false,
		completionFn: func(ctx context.Context, req *llm.ChatRequest) (*llm.ChatResponse, error) {
			capturedReq = req
			// 返回普通文本响应（不含工具调用），避免触发 ReAct 循环
			return &llm.ChatResponse{
				Choices: []llm.ChatChoice{{
					Message:      types.Message{Content: "I found the answer: 42."},
					FinishReason: "stop",
				}},
			}, nil
		},
	}
	toolMgr := &testToolManager{
		getAllowedToolsFn: func(agentID string) []types.ToolSchema {
			return []types.ToolSchema{{
				Name:        "search",
				Description: "search tool",
				Parameters:  json.RawMessage(`{"type":"object","properties":{"query":{"type":"string"}}}`),
			}}
		},
	}

	config := testAgentConfig("test-dual-fc", "Dual FC Agent", "claude-sonnet-4-6")
	config.Runtime.Tools = []string{"search"}

	agent := BuildBaseAgent(config, testGatewayFromProvider(mainProvider), nil, toolMgr, nil, logger, nil)
	setTestToolProvider(agent, toolProvider)

	resp, err := agent.ChatCompletion(context.Background(), []types.Message{
		{Role: llm.RoleUser, Content: "search something"},
	})

	// 不应报错，应自动降级（不再返回 ErrToolProviderNotSupported）
	require.NoError(t, err)
	require.NotNil(t, resp)

	// 请求中的 ToolCallMode 应为 XML
	require.NotNil(t, capturedReq)
	assert.Equal(t, llm.ToolCallModeXML, capturedReq.ToolCallMode)

	// XMLToolRewriter 应已将工具注入 system prompt 并清除 req.Tools
	assert.Nil(t, capturedReq.Tools, "XML 模式下 req.Tools 应被清除")

	// system prompt 应包含工具定义
	hasToolInSystemPrompt := false
	for _, msg := range capturedReq.Messages {
		if msg.Role == types.RoleSystem && strings.Contains(msg.Content, "search") && strings.Contains(msg.Content, "<tool_calls>") {
			hasToolInSystemPrompt = true
			break
		}
	}
	assert.True(t, hasToolInSystemPrompt, "system prompt 应包含工具定义")
}

// TestToolProvider_XMLFallback_StreamCompletion 流式模式下 XML 降级
// 注意：StreamCompletion 使用 chatProvider（主 provider），
// 当 chatProvider 也不支持 FC 时才会降级
func TestToolProvider_XMLFallback_StreamCompletion(t *testing.T) {
	logger := zap.NewNop()

	// mainProvider 不支持 FC → 降级到 XML
	var capturedReq *llm.ChatRequest
	mainProvider := &testProvider{
		name:           "main-no-fc",
		supportsNative: false,
		streamFn: func(ctx context.Context, req *llm.ChatRequest) (<-chan llm.StreamChunk, error) {
			capturedReq = req
			ch := make(chan llm.StreamChunk, 1)
			ch <- llm.StreamChunk{
				Delta:        types.Message{Content: "No tools needed."},
				FinishReason: "stop",
			}
			close(ch)
			return ch, nil
		},
	}
	toolMgr := &testToolManager{
		getAllowedToolsFn: func(agentID string) []types.ToolSchema {
			return []types.ToolSchema{{Name: "search", Description: "search tool"}}
		},
	}

	config := testAgentConfig("test-dual-fc-stream", "Dual FC Stream Agent", "claude-sonnet-4-6")
	config.Runtime.Tools = []string{"search"}

	agent := BuildBaseAgent(config, testGatewayFromProvider(mainProvider), nil, toolMgr, nil, logger, nil)
	// 不设置 toolProvider → chatProvider = mainProvider → 降级到 XML

	ch, err := agent.StreamCompletion(context.Background(), []types.Message{
		{Role: llm.RoleUser, Content: "search something"},
	})

	// 不应报错，应自动降级（不再返回 ErrToolProviderNotSupported）
	require.NoError(t, err)
	require.NotNil(t, ch)

	var chunks []llm.StreamChunk
	for c := range ch {
		chunks = append(chunks, c)
	}
	assert.NotEmpty(t, chunks)

	// 验证请求被设置为 XML 模式
	require.NotNil(t, capturedReq)
	assert.Equal(t, llm.ToolCallModeXML, capturedReq.ToolCallMode)
	assert.Nil(t, capturedReq.Tools, "XML 模式下 req.Tools 应被清除")
}

// TestToolProvider_XMLFallback_NilToolProvider toolProvider 为 nil 时退化到 mainProvider，
// 若 mainProvider 也不支持 FC 则降级到 XML
func TestToolProvider_XMLFallback_NilToolProvider(t *testing.T) {
	logger := zap.NewNop()

	var capturedReq *llm.ChatRequest
	mainProvider := &testProvider{
		name:           "main-no-fc",
		supportsNative: false,
		completionFn: func(ctx context.Context, req *llm.ChatRequest) (*llm.ChatResponse, error) {
			capturedReq = req
			return &llm.ChatResponse{
				Choices: []llm.ChatChoice{{
					Message:      types.Message{Content: "No tool calls here."},
					FinishReason: "stop",
				}},
			}, nil
		},
	}
	toolMgr := &testToolManager{
		getAllowedToolsFn: func(agentID string) []types.ToolSchema {
			return []types.ToolSchema{{Name: "search", Description: "search tool"}}
		},
	}

	config := testAgentConfig("test-fc-nil-tp", "FC Nil ToolProvider Agent", "claude-sonnet-4-6")
	config.Runtime.Tools = []string{"search"}

	agent := BuildBaseAgent(config, testGatewayFromProvider(mainProvider), nil, toolMgr, nil, logger, nil)
	// 不设置 toolProvider → 退化到 mainProvider

	resp, err := agent.ChatCompletion(context.Background(), []types.Message{
		{Role: llm.RoleUser, Content: "search something"},
	})

	// 不应报错，应降级到 XML
	require.NoError(t, err)
	require.NotNil(t, resp)

	require.NotNil(t, capturedReq)
	assert.Equal(t, llm.ToolCallModeXML, capturedReq.ToolCallMode)
}

// TestToolProvider_BuilderWithoutToolProvider Builder 不设置 toolProvider
func TestToolProvider_BuilderWithoutToolProvider(t *testing.T) {
	logger := zap.NewNop()
	mainProvider := &testProvider{name: "main"}

	config := testAgentConfig("test-builder-single", "Builder Single Agent", "claude-sonnet-4-6")

	agent, err := NewAgentBuilder(config).WithGateway(testGatewayFromProvider(
		mainProvider)).
		WithLogger(logger).
		Build()

	assert.NoError(t, err)
	assert.NotNil(t, agent)
	assert.Equal(t, mainProvider, testMainProvider(agent))
	assert.Nil(t, testToolProvider(agent), "不设置 toolProvider 时应为 nil")
}
